on: [push, pull_request]

name: CI

jobs:
  android:
    name: Compile Android
    runs-on: ubuntu-latest
    steps:
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm/10.0
          key: cached-llvm-10.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '10.0'
          directory: ${{ runner.temp }}/llvm/10.0
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v1

      - name: Setup Android NDK (Location)
        run: mkdir /tmp/toolchains

      - name: Install Android NDK
        uses: ravinderjangra/android-ndk-toolchain-setup@0.2
        with:
          api: '28'
          arch: 'x86'
          install-location: '/tmp/toolchains'
          force: true

      - name: Set Android NDK Env
        run: echo '::set-env name=ANDROID_NDK_HOME::/tmp/toolchains'

      - name: Install Android Targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

      - name: Install Cargo Make
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: install
          args: --force cargo-make

      - name: Run cargo make android
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: android
