on: [push, pull_request]

name: CI

jobs:
  android:
    name: Compile Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v1

      - name: Setup Android NDK (Location)
        run: mkdir toolchains

      - name: Install Android NDK
        uses: ravinderjangra/android-ndk-toolchain-setup@0.2
        with:
          api: '28'
          arch: 'x86'
          install-location: 'toolchains'
          force: true

      - name: Inspect Android NDK
        run: ls toolchains

      - name: Install Android Targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

      - name: Install Cargo Make
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: install
          args: --froce cargo-make

      - name: Run cargo make android
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: android
